### ISSUE TITLE
Can't place order

### ISSUE THREAD

**Issue by phgdl195** [mundipagg/magento2#3]
### Status

BUG REPORT / TASK

### Checklist

Add checklist if this is a task

- [x] Add slack integration
- [_] Support xyz 

### Steps

1. Login
2. Add product to cart
3. Go to Checkout
5. Select shipping method
5. Select Billet and Place Order

### Expected behaviour

Place Order

### Actual behaviour

the store gives me an error saying that a server error occurred

### Environment

Magento 2.2.2 C.E Only with ESPL_Onepagecheckout and Mundipagg_Mundipagg instaled

### Logs / Stack trace

```
$ cat mundipagg-2018-03-06.log 
2018-03-06T04:06:56+00:00 INFO (6): array (
  'items' => 
  array (
    0 => 
    array (
      'amount' => 5990.0,
      'description' => 'product',
      'quantity' => 2,
    ),
  ),
  'customer' => 
  array (
    'name' => 'Luiz  Fernando',
    'email' => 'teste2@teste.com',
    'document' => '090.380.889-73',
    'type' => 'individual',
    'address' => 
    array (
      'street' => 'Lima',
      'number' => '123',
      'complement' => 'Endereço',
      'zip_code' => '86.025901',
      'neighborhood' => '123',
      'city' => 'Cidade',
      'state' => 'AL',
      'country' => 'BR',
    ),
  ),
  'payments' => 
  array (
    0 => 
    array (
      'amount' => 20980.0,
      'payment_method' => 'boleto',
      'capture' => false,
      'boleto' => 
      array (
        'bank' => '341',
        'instructions' => NULL,
        'due_at' => '2018-03-11T00:00:00Z',
      ),
    ),
  ),
  'code' => '000000030',
  'customer_id' => NULL,
  'shipping' => 
  array (
    'amount' => 9000.0,
    'description' => '.',
    'address' => 
    array (
      'street' => 'Lima',
      'number' => '123',
      'complement' => 'Endereço',
      'zip_code' => '86.025901',
      'neighborhood' => '123',
      'city' => 'Cidade',
      'state' => 'AL',
      'country' => 'BR',
    ),
  ),
  'metadata' => 
  array (
    'module_name' => 'Magento 2',
    'module_version' => '1.2.14',
  ),
  'closed' => true,
  'antifraud_enabled' => NULL,
  'ip' => '127.0.0.1',
  'session_id' => NULL,
  'location' => NULL,
  'device' => NULL,
)
2018-03-06T04:06:57+00:00 INFO (6): MundiAPILib\Exceptions\ErrorException: Authorization has been denied for this request. in /var/www/vitaringa/vendor/mundipagg/mundiapi/src/Controllers/BaseController.php:75
Stack trace:
#0 /var/www/vitaringa/vendor/mundipagg/mundiapi/src/Controllers/OrdersController.php(152): MundiAPILib\Controllers\BaseController->validateResponse(Object(MundiAPILib\Http\HttpResponse), Object(MundiAPILib\Http\HttpContext))
#1 /var/www/vitaringa/vendor/mundipagg/mundipagg-magento2-module/Gateway/Transaction/Billet/ResourceGateway/Create/RequestBuilder.php(229): MundiAPILib\Controllers\OrdersController->createOrder(Object(MundiAPILib\Models\CreateOrderRequest))
#2 /var/www/vitaringa/vendor/mundipagg/mundipagg-magento2-module/Gateway/Transaction/Billet/ResourceGateway/Create/RequestBuilder.php(100): MundiPagg\MundiPagg\Gateway\Transaction\Billet\ResourceGateway\Create\RequestBuilder->createNewRequest(Object(MundiPagg\MundiPagg\Gateway\Transaction\Billet\ResourceGateway\Create\RequestDataProvider))
#3 /var/www/vitaringa/vendor/mundipagg/mundipagg-magento2-module/Gateway/Transaction/Base/Command/AbstractApiCommand.php(48): MundiPagg\MundiPagg\Gateway\Transaction\Billet\ResourceGateway\Create\RequestBuilder->build(Array)
#4 /var/www/vitaringa/vendor/magento/module-payment/Model/Method/Adapter.php(546): MundiPagg\MundiPagg\Gateway\Transaction\Base\Command\AbstractApiCommand->execute(Array)
#5 /var/www/vitaringa/vendor/magento/module-payment/Model/Method/Adapter.php(448): Magento\Payment\Model\Method\Adapter->executeCommand('authorize', Array)
#6 /var/www/vitaringa/generated/code/Magento/Payment/Model/Method/Adapter/Interceptor.php(349): Magento\Payment\Model\Method\Adapter->authorize(Object(Magento\Sales\Model\Order\Payment\Interceptor), 209.8)
#7 /var/www/vitaringa/vendor/magento/module-sales/Model/Order/Payment/Operations/AuthorizeOperation.php(45): Magento\Payment\Model\Method\Adapter\Interceptor->authorize(Object(Magento\Sales\Model\Order\Payment\Interceptor), 209.8)
#8 /var/www/vitaringa/vendor/magento/module-sales/Model/Order/Payment/Processor.php(72): Magento\Sales\Model\Order\Payment\Operations\AuthorizeOperation->authorize(Object(Magento\Sales\Model\Order\Payment\Interceptor), true, 209.8)
#9 /var/www/vitaringa/vendor/magento/module-sales/Model/Order/Payment.php(1107): Magento\Sales\Model\Order\Payment\Processor->authorize(Object(Magento\Sales\Model\Order\Payment\Interceptor), true, 209.8)
#10 /var/www/vitaringa/generated/code/Magento/Sales/Model/Order/Payment/Interceptor.php(427): Magento\Sales\Model\Order\Payment->authorize(true, 209.8)
#11 /var/www/vitaringa/vendor/mundipagg/mundipagg-magento2-module/Gateway/Transaction/Base/Command/InitializeCommand.php(42): Magento\Sales\Model\Order\Payment\Interceptor->authorize(true, 209.8)
#12 /var/www/vitaringa/vendor/magento/module-payment/Model/Method/Adapter.php(546): MundiPagg\MundiPagg\Gateway\Transaction\Base\Command\InitializeCommand->execute(Array)
#13 /var/www/vitaringa/vendor/magento/module-payment/Model/Method/Adapter.php(652): Magento\Payment\Model\Method\Adapter->executeCommand('initialize', Array)
#14 /var/www/vitaringa/generated/code/Magento/Payment/Model/Method/Adapter/Interceptor.php(557): Magento\Payment\Model\Method\Adapter->initialize('authorize', Object(Magento\Framework\DataObject))
#15 /var/www/vitaringa/vendor/magento/module-sales/Model/Order/Payment.php(360): Magento\Payment\Model\Method\Adapter\Interceptor->initialize('authorize', Object(Magento\Framework\DataObject))
#16 /var/www/vitaringa/generated/code/Magento/Sales/Model/Order/Payment/Interceptor.php(167): Magento\Sales\Model\Order\Payment->place()
#17 /var/www/vitaringa/vendor/magento/module-sales/Model/Order.php(862): Magento\Sales\Model\Order\Payment\Interceptor->place()
#18 /var/www/vitaringa/vendor/magento/module-sales/Model/Order.php(1051): Magento\Sales\Model\Order->_placePayment()
#19 /var/www/vitaringa/generated/code/Magento/Sales/Model/Order/Interceptor.php(479): Magento\Sales\Model\Order->place()
#20 /var/www/vitaringa/vendor/magento/module-sales/Model/Service/OrderService.php(191): Magento\Sales\Model\Order\Interceptor->place()
#21 /var/www/vitaringa/vendor/magento/module-quote/Model/QuoteManagement.php(511): Magento\Sales\Model\Service\OrderService->place(Object(Magento\Sales\Model\Order\Interceptor))
#22 /var/www/vitaringa/vendor/magento/module-quote/Model/QuoteManagement.php(406): Magento\Quote\Model\QuoteManagement->submitQuote(Object(Magento\Quote\Model\Quote), Array)
#23 /var/www/vitaringa/vendor/magento/module-quote/Model/QuoteManagement.php(364): Magento\Quote\Model\QuoteManagement->submit(Object(Magento\Quote\Model\Quote))
#24 /var/www/vitaringa/vendor/magento/module-checkout/Model/PaymentInformationManagement.php(83): Magento\Quote\Model\QuoteManagement->placeOrder(22)
#25 /var/www/vitaringa/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Checkout\Model\PaymentInformationManagement->savePaymentInformationAndPlaceOrder(22, Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address))
#26 /var/www/vitaringa/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->___callParent('savePaymentInfo...', Array)
#27 /var/www/vitaringa/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->Magento\Framework\Interception\{closure}(22, Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address))
#28 /var/www/vitaringa/generated/code/Magento/Checkout/Model/PaymentInformationManagement/Interceptor.php(26): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->___callPlugins('savePaymentInfo...', Array, Array)
#29 [internal function]: Magento\Checkout\Model\PaymentInformationManagement\Interceptor->savePaymentInformationAndPlaceOrder(22, Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address))
#30 /var/www/vitaringa/vendor/magento/module-webapi/Controller/Rest.php(330): call_user_func_array(Array, Array)
#31 /var/www/vitaringa/vendor/magento/module-webapi/Controller/Rest.php(239): Magento\Webapi\Controller\Rest->processApiRequest()
#32 /var/www/vitaringa/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#33 /var/www/vitaringa/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent('dispatch', Array)
#34 /var/www/vitaringa/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#35 /var/www/vitaringa/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(39): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins('dispatch', Array, Array)
#36 /var/www/vitaringa/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#37 /var/www/vitaringa/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#38 /var/www/vitaringa/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http\Interceptor->launch()
#39 /var/www/vitaringa/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#40 {main}
```

**Comment by felipebool** [comment]
"Authorization has been denied for this request"

Have you checked your secret keys?
