### ISSUE TITLE
InvalidArgumentException: Por favor digite um e-mail de cliente

### ISSUE THREAD

**Issue by arielcugenotta** [mundipagg/magento2#7]
### Passos

1. Adicionei o produto no carrinho
2. Fui para o checkout e preenchi o e-mail e todos os campos de endereço
3. Finalizei como GUEST a compra por cartão de crédito

### Comportamento Esperado

Tela de sucesso e pedido gravado dentro do painel de vocês e do Magento.

### Comportamento Atual

Aparece uma mensagem de erro no servidor, acima das opções de pagamento.

### Informações Adicionais

Isso não ocorre na versão 1.2.17 do módulo, acredito que foram os últimos commits que causaram esse erro.

### Ambiente

Ubuntu
PHP 7.0.2
Magento 2.1.9
Módulo versão 1.2.20

### Logs / Stack trace

```
2018-05-11T21:33:59+00:00 INFO (6): InvalidArgumentException: Por favor digite um e-mail de cliente. in /home/vcloud/public_html/#######################/vendor/mundipagg/mundipagg-magento2-module/Helper/CustomerCustomAttributesHelper.php:53
Stack trace:
#0 /home/vcloud/public_html/#######################/vendor/mundipagg/mundipagg-magento2-module/Gateway/Transaction/CreditCard/ResourceGateway/Create/RequestBuilder.php(470): MundiPagg\MundiPagg\Helper\CustomerCustomAttributesHelper->setCustomerCustomAttribute(Object(Magento\Customer\Model\Data\Customer), Object(MundiAPILib\Models\GetOrderResponse), '0')
#1 /home/vcloud/public_html/#######################/vendor/mundipagg/mundipagg-magento2-module/Gateway/Transaction/CreditCard/ResourceGateway/Create/RequestBuilder.php(108): MundiPagg\MundiPagg\Gateway\Transaction\CreditCard\ResourceGateway\Create\RequestBuilder->createNewRequest(Object(MundiPagg\MundiPagg\Gateway\Transaction\CreditCard\ResourceGateway\Create\RequestDataProvider))
#2 /home/vcloud/public_html/#######################/vendor/mundipagg/mundipagg-magento2-module/Gateway/Transaction/Base/Command/AbstractApiCommand.php(48): MundiPagg\MundiPagg\Gateway\Transaction\CreditCard\ResourceGateway\Create\RequestBuilder->build(Array)
#3 /home/vcloud/public_html/#######################/vendor/magento/module-payment/Model/Method/Adapter.php(530): MundiPagg\MundiPagg\Gateway\Transaction\Base\Command\AbstractApiCommand->execute(Array)
#4 /home/vcloud/public_html/#######################/vendor/magento/module-payment/Model/Method/Adapter.php(432): Magento\Payment\Model\Method\Adapter->executeCommand('authorize', Array)
#5 /home/vcloud/public_html/#######################/vendor/magento/module-sales/Model/Order/Payment/Operations/AuthorizeOperation.php(45): Magento\Payment\Model\Method\Adapter->authorize(Object(Magento\Sales\Model\Order\Payment\Interceptor), 20.1)
#6 /home/vcloud/public_html/#######################/vendor/magento/module-sales/Model/Order/Payment/Processor.php(72): Magento\Sales\Model\Order\Payment\Operations\AuthorizeOperation->authorize(Object(Magento\Sales\Model\Order\Payment\Interceptor), true, 20.1)
#7 /home/vcloud/public_html/#######################/vendor/magento/module-sales/Model/Order/Payment.php(1054): Magento\Sales\Model\Order\Payment\Processor->authorize(Object(Magento\Sales\Model\Order\Payment\Interceptor), true, 20.1)
#8 /home/vcloud/public_html/#######################/vendor/mundipagg/mundipagg-magento2-module/Gateway/Transaction/Base/Command/InitializeCommand.php(42): Magento\Sales\Model\Order\Payment->authorize(true, 20.1)
#9 /home/vcloud/public_html/#######################/vendor/magento/module-payment/Model/Method/Adapter.php(530): MundiPagg\MundiPagg\Gateway\Transaction\Base\Command\InitializeCommand->execute(Array)
#10 /home/vcloud/public_html/#######################/vendor/magento/module-payment/Model/Method/Adapter.php(637): Magento\Payment\Model\Method\Adapter->executeCommand('initialize', Array)
#11 /home/vcloud/public_html/#######################/vendor/magento/module-sales/Model/Order/Payment.php(340): Magento\Payment\Model\Method\Adapter->initialize('authorize_captu...', Object(Magento\Framework\DataObject))
#12 /home/vcloud/public_html/#######################/vendor/magento/module-sales/Model/Order.php(858): Magento\Sales\Model\Order\Payment->place()
#13 /home/vcloud/public_html/#######################/vendor/magento/module-sales/Model/Order.php(1047): Magento\Sales\Model\Order->_placePayment()
#14 /home/vcloud/public_html/#######################/vendor/magento/module-sales/Model/Service/OrderService.php(190): Magento\Sales\Model\Order->place()
#15 /home/vcloud/public_html/#######################/vendor/magento/module-quote/Model/QuoteManagement.php(488): Magento\Sales\Model\Service\OrderService->place(Object(Magento\Sales\Model\Order))
#16 /home/vcloud/public_html/#######################/vendor/magento/module-quote/Model/QuoteManagement.php(391): Magento\Quote\Model\QuoteManagement->submitQuote(Object(Magento\Quote\Model\Quote), Array)
#17 /home/vcloud/public_html/#######################/vendor/magento/module-quote/Model/QuoteManagement.php(349): Magento\Quote\Model\QuoteManagement->submit(Object(Magento\Quote\Model\Quote))
#18 /home/vcloud/public_html/#######################/vendor/magento/module-quote/Model/GuestCart/GuestCartManagement.php(87): Magento\Quote\Model\QuoteManagement->placeOrder('538', NULL)
#19 /home/vcloud/public_html/#######################/vendor/magento/module-checkout/Model/GuestPaymentInformationManagement.php(90): Magento\Quote\Model\GuestCart\GuestCartManagement->placeOrder('2e1d9a265c8c321...')
#20 [internal function]: Magento\Checkout\Model\GuestPaymentInformationManagement->savePaymentInformationAndPlaceOrder('2e1d9a265c8c321...', 'ariel@mestremag...', Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address))
#21 /home/vcloud/public_html/#######################/vendor/magento/module-webapi/Controller/Rest.php(307): call_user_func_array(Array, Array)
#22 /home/vcloud/public_html/#######################/vendor/magento/module-webapi/Controller/Rest.php(216): Magento\Webapi\Controller\Rest->processApiRequest()
#23 /home/vcloud/public_html/#######################/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(24): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#24 /home/vcloud/public_html/#######################/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#25 /home/vcloud/public_html/#######################/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#26 /home/vcloud/public_html/#######################/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#27 {main}
```

**Comment by michelpl** [comment]
@arielcugenotta, estou conseguindo fazer testes no site em produção de vocês. Vocês mudaram alguma coisa?

**Comment by michelpl** [comment]
@arielcugenotta, lançamos novas versões em que esse comportamento não se repetiu.
Se o problema persistir, favor reabrir a issue ou entrar em contato através do nosso suporte.
